[package]
name = "aoc_2020_rust"
version = "0.1.0"
authors = ["robinch <robinch88@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
